version: '3.3'
services:
  erp-system-server:
    image: ghacupha/erp-system:0.1.5-SNAPSHOT
    volumes:
      - ./logs/:/logs/
      - ./reports-directory/:/reports-directory/
      - ./generated-reports/:/generated-reports/
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      #- SPRING_DATASOURCE_URL=jdbc:postgresql://erpsystem-postgresql:5432/erpSystem
      #- SPRING_LIQUIBASE_URL=jdbc:postgresql://erpsystem-postgresql:5432/erpSystem
      - SPRING_DATASOURCE_URL=${LOCAL_PG_SERVER}/${ERP_SYSTEM_PROD_DB}
      - SPRING_LIQUIBASE_URL=${LOCAL_PG_SERVER}/${ERP_SYSTEM_PROD_DB}
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      #- SPRING_ELASTICSEARCH_REST_URIS=http://erpsystem-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=${SPRING_DATA_JEST_URI}
      - ERP_SYSTEM_PROD_DB=${ERP_SYSTEM_PROD_DB}
      - ERP_SYSTEM_DEV_DB=${ERP_SYSTEM_DEV_DB}
      - ERP_SYSTEM_PORT=${ERP_SYSTEM_PORT}
      - PG_DATABASE_DEV_USER=${PG_DATABASE_DEV_USER}
      - PG_DATABASE_PROD_USER=${PG_DATABASE_PROD_USER}
      - PG_DATABASE_DEV_PASSWORD=${PG_DATABASE_DEV_PASSWORD}
      - PG_DATABASE_PROD_PASSWORD=${PG_DATABASE_PROD_PASSWORD}
      - LOCAL_PG_SERVER=${LOCAL_PG_SERVER}
      - ERP_SYSTEM_DEV_PORT=${ERP_SYSTEM_DEV_PORT}
      - ERP_SYSTEM_PROD_PORT=${ERP_SYSTEM_PROD_PORT}
      - ERP_SYSTEM_PROD_MAIL_BASE_URL=${ERP_SYSTEM_PROD_MAIL_BASE_URL}
      - ERP_SYSTEM_DEV_MAIL_BASE_URL=${ERP_SYSTEM_DEV_MAIL_BASE_URL}
      - SECURITY_AUTHENTICATION_JWT_BASE64_SECRET=${SECURITY_AUTHENTICATION_JWT_BASE64_SECRET}
      - UPLOADS_SIZE=${UPLOADS_SIZE}
      - SANDBOX_INSTANCE_URLS=${SANDBOX_INSTANCE_URLS}
      # - LOGGING_CONFIG=${LOGGING_CONFIG}
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      #- 8980:8980
      - ${ERP_SERVER_DEPLOYMENT_PROD_PORT}